language: node_js
node_js:
  - "4.3"
before_install:
  - wget https://download.rethinkdb.com/dist/rethinkdb-2.2.6.tgz && tar xf rethinkdb-2.2.6.tgz && cd rethinkdb-2.2.6 && ./configure --allow-fetch && make
  - rethinkdb --version
  - rethinkdb --daemon
script:
  - npm run test
  - npm run lint
